import SwiftUI

enum TokenTrackerAttachmentEdge {
    case left
    case right
    case bottom
}

/// A single continuous silhouette for an edge-attached provider surface.
/// Side variants are generated by mirroring the same left-hand path.
struct TokenTrackerEdgeProtrusionShape: Shape {
    let attachmentEdge: TokenTrackerAttachmentEdge

    func path(in rect: CGRect) -> Path {
        switch self.attachmentEdge {
        case .left:
            self.rightAttachedPath(width: rect.width, height: rect.height).applying(CGAffineTransform(
                a: -1,
                b: 0,
                c: 0,
                d: 1,
                tx: rect.maxX,
                ty: rect.minY))
        case .right:
            self.rightAttachedPath(width: rect.width, height: rect.height)
                .applying(CGAffineTransform(translationX: rect.minX, y: rect.minY))
        case .bottom:
            self.rightAttachedPath(width: rect.height, height: rect.width).applying(CGAffineTransform(
                a: 0,
                b: -1,
                c: 1,
                d: 0,
                tx: rect.minX,
                ty: rect.minY + rect.height))
        }
    }

    private func rightAttachedPath(width requestedWidth: CGFloat, height requestedHeight: CGFloat) -> Path {
        let width = max(requestedWidth, 0)
        let height = max(requestedHeight, 0)
        let radius = min(5 * width / 12, height / 4)
        let kappa: CGFloat = 0.552_284_749_8
        var path = Path()

        path.move(to: CGPoint(x: width, y: 0))
        path.addCurve(
            to: CGPoint(x: width - radius, y: radius),
            control1: CGPoint(x: width, y: kappa * radius),
            control2: CGPoint(x: width - (1 - kappa) * radius, y: radius))
        path.addLine(to: CGPoint(x: radius, y: radius))
        path.addCurve(
            to: CGPoint(x: 0, y: 2 * radius),
            control1: CGPoint(x: radius - kappa * radius, y: radius),
            control2: CGPoint(x: 0, y: 2 * radius - kappa * radius))
        path.addLine(to: CGPoint(x: 0, y: height - 2 * radius))
        path.addCurve(
            to: CGPoint(x: radius, y: height - radius),
            control1: CGPoint(x: 0, y: height - 2 * radius + kappa * radius),
            control2: CGPoint(x: radius - kappa * radius, y: height - radius))
        path.addLine(to: CGPoint(x: width - radius, y: height - radius))
        path.addCurve(
            to: CGPoint(x: width, y: height),
            control1: CGPoint(x: width - (1 - kappa) * radius, y: height - radius),
            control2: CGPoint(x: width, y: height - kappa * radius))
        path.addLine(to: CGPoint(x: width, y: 0))
        path.closeSubpath()
        return path
    }
}

enum TokenTrackerCalloutArrowEdge {
    case left
    case right
    case bottom
}

struct TokenTrackerProviderDetailCalloutShape: Shape {
    let arrowEdge: TokenTrackerCalloutArrowEdge
    let arrowOffset: CGFloat

    func path(in rect: CGRect) -> Path {
        switch self.arrowEdge {
        case .left:
            self.leftPath(in: rect)
        case .right:
            self.leftPath(in: rect).applying(CGAffineTransform(
                a: -1,
                b: 0,
                c: 0,
                d: 1,
                tx: rect.minX + rect.maxX,
                ty: 0))
        case .bottom:
            self.bottomCalloutPath(in: rect)
        }
    }

    private func leftPath(in rect: CGRect) -> Path {
        let body = CGRect(
            x: rect.minX + TokenTrackerCalloutGeometry.arrowLength,
            y: rect.minY,
            width: max(rect.width - TokenTrackerCalloutGeometry.arrowLength, 0),
            height: rect.height)
        let radius = min(
            TokenTrackerCalloutGeometry.cornerRadius,
            min(body.width, body.height) / 2)
        let offset = TokenTrackerCalloutGeometry.clampArrowOffset(
            self.arrowOffset,
            edgeLength: body.height)
        let base = min(TokenTrackerCalloutGeometry.arrowBase / 2, body.height / 2)
        var path = Path()

        path.move(to: CGPoint(x: body.minX + radius, y: body.minY))
        path.addLine(to: CGPoint(x: body.maxX - radius, y: body.minY))
        path.addCurve(
            to: CGPoint(x: body.maxX, y: body.minY + radius),
            control1: CGPoint(x: body.maxX - radius / 2, y: body.minY),
            control2: CGPoint(x: body.maxX, y: body.minY + radius / 2))
        path.addLine(to: CGPoint(x: body.maxX, y: body.maxY - radius))
        path.addCurve(
            to: CGPoint(x: body.maxX - radius, y: body.maxY),
            control1: CGPoint(x: body.maxX, y: body.maxY - radius / 2),
            control2: CGPoint(x: body.maxX - radius / 2, y: body.maxY))
        path.addLine(to: CGPoint(x: body.minX + radius, y: body.maxY))
        path.addCurve(
            to: CGPoint(x: body.minX, y: body.maxY - radius),
            control1: CGPoint(x: body.minX + radius / 2, y: body.maxY),
            control2: CGPoint(x: body.minX, y: body.maxY - radius / 2))
        path.addLine(to: CGPoint(x: body.minX, y: body.minY + offset + base))
        path.addLine(to: CGPoint(x: rect.minX, y: body.minY + offset))
        path.addLine(to: CGPoint(x: body.minX, y: body.minY + offset - base))
        path.addLine(to: CGPoint(x: body.minX, y: body.minY + radius))
        path.addCurve(
            to: CGPoint(x: body.minX + radius, y: body.minY),
            control1: CGPoint(x: body.minX, y: body.minY + radius / 2),
            control2: CGPoint(x: body.minX + radius / 2, y: body.minY))
        path.closeSubpath()
        return path
    }

    private func bottomCalloutPath(in rect: CGRect) -> Path {
        let body = CGRect(
            x: rect.minX,
            y: rect.minY,
            width: rect.width,
            height: max(rect.height - TokenTrackerCalloutGeometry.arrowLength, 0))
        let radius = min(
            TokenTrackerCalloutGeometry.cornerRadius,
            min(body.width, body.height) / 2)
        let offset = TokenTrackerCalloutGeometry.clampArrowOffset(
            self.arrowOffset,
            edgeLength: body.width)
        let base = min(TokenTrackerCalloutGeometry.arrowBase / 2, body.width / 2)
        var path = Path()

        path.move(to: CGPoint(x: body.minX + radius, y: body.minY))
        path.addLine(to: CGPoint(x: body.maxX - radius, y: body.minY))
        path.addCurve(
            to: CGPoint(x: body.maxX, y: body.minY + radius),
            control1: CGPoint(x: body.maxX - radius / 2, y: body.minY),
            control2: CGPoint(x: body.maxX, y: body.minY + radius / 2))
        path.addLine(to: CGPoint(x: body.maxX, y: body.maxY - radius))
        path.addCurve(
            to: CGPoint(x: body.maxX - radius, y: body.maxY),
            control1: CGPoint(x: body.maxX, y: body.maxY - radius / 2),
            control2: CGPoint(x: body.maxX - radius / 2, y: body.maxY))
        path.addLine(to: CGPoint(x: body.minX + offset + base, y: body.maxY))
        path.addLine(to: CGPoint(x: body.minX + offset, y: rect.maxY))
        path.addLine(to: CGPoint(x: body.minX + offset - base, y: body.maxY))
        path.addLine(to: CGPoint(x: body.minX + radius, y: body.maxY))
        path.addCurve(
            to: CGPoint(x: body.minX, y: body.maxY - radius),
            control1: CGPoint(x: body.minX + radius / 2, y: body.maxY),
            control2: CGPoint(x: body.minX, y: body.maxY - radius / 2))
        path.addLine(to: CGPoint(x: body.minX, y: body.minY + radius))
        path.addCurve(
            to: CGPoint(x: body.minX + radius, y: body.minY),
            control1: CGPoint(x: body.minX, y: body.minY + radius / 2),
            control2: CGPoint(x: body.minX + radius / 2, y: body.minY))
        path.closeSubpath()
        return path
    }
}

enum TokenTrackerCalloutGeometry {
    static let arrowLength: CGFloat = 14
    static let arrowBase: CGFloat = 20
    static let cornerRadius: CGFloat = 18
    static let arrowCornerClearance: CGFloat = 28

    static func clampArrowOffset(_ offset: CGFloat, edgeLength: CGFloat) -> CGFloat {
        guard edgeLength.isFinite, edgeLength > 0 else { return 0 }
        let lower = min(self.arrowCornerClearance, edgeLength / 2)
        let upper = max(lower, edgeLength - self.arrowCornerClearance)
        return min(max(offset.isFinite ? offset : edgeLength / 2, lower), upper)
    }

    static func arrowOffset(
        logoCenter: CGPoint,
        panelFrame: CGRect,
        edge: TokenTrackerCalloutArrowEdge) -> CGFloat
    {
        guard panelFrame.origin.x.isFinite, panelFrame.origin.y.isFinite,
              panelFrame.width.isFinite, panelFrame.height.isFinite,
              panelFrame.width > 0, panelFrame.height > 0,
              logoCenter.x.isFinite, logoCenter.y.isFinite
        else {
            return 0
        }
        switch edge {
        case .left, .right:
            return self.clampArrowOffset(
                panelFrame.maxY - logoCenter.y,
                edgeLength: panelFrame.height)
        case .bottom:
            return self.clampArrowOffset(
                logoCenter.x - panelFrame.minX,
                edgeLength: panelFrame.width)
        }
    }
}
